In [ ]:
import pandas as pd

import mysql.connector
import configparser
from openpyxl import Workbook

import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font

In [65]:
# Crea el dataframe de ejemplo
df = pd.DataFrame({'A': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                   'B': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                   'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                   'D': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]})


# Funci√≥n para insertar filas con subtotal y calcular subtotales
    # Obtener las columnas num√©ricas
    # Obtener el nombre de la columna de √≠ndice
    # Obtener Grupo actual: inicialmente el primer valor de la primera columna
    # Diccionario para almacenar subtotales del grupo actual
    # Lista para almacenar filas a concatenar
    # Iterar sobre las filas del DataFrame para calcular subtotales y agregar filas de subtotal
        # Compara el valor actual de la columna de agrupaci√≥n con la fila anterior
            
            # En caso de que el valor de la columna de agrupaci√≥n sea "diferente" al grupo actual:
            # Crea una fila con el nombre del grupo
            # A√±ade los subtotales al diccionario
            # A√±ade la fila de subtotal a la lista de filas a concatenar
            # Reinicia los subtotales para el nuevo grupo
            # Actualiza el grupo actual con el valor de la fila actual
        
        # En caso de que el valor de la columna de agrupaci√≥n sea "igual" al grupo actual:
        # Actualiza los subtotales del grupo actual
        # Agrega la fila actual al final de las filas a concatenar

    # Agregar los subtotales del √∫ltimo grupo y concatenar las filas de subtotal al DataFrame original


# ===============================================================================================================

    # Aplica la funci√≥n para insertar filas con subtotal y calcular subtotales
    # Imprime el dataframe con las filas insertadas, subtotales y subtotales calculados
    
    # Concatena las filas de subtotal al DataFrame original 

# Funci√≥n para insertar filas con subtotal y calcular subtotales
def insertar_fila_subtotal(df):
    """
    Inserta una fila en blanco con "Subtotal" y calcula los subtotales de cada grupo en las columnas num√©ricas.
    Argumentos: df (pandas.DataFrame): El dataframe a procesar.
    Devuelve: pandas.DataFrame: El dataframe con las filas insertadas, subtotales y subtotales calculados.
    """
    # Obtener las columnas num√©ricas
    columnas_numericas = df.select_dtypes(include='number').columns
    print('Columnas num√©ricas: ', columnas_numericas)
    print("="*50)
    
    # Obtener el nombre de la columna de √≠ndice
    indice_columna = df.columns.tolist().index(columnas_numericas[0])
    print('Indice de columna: ',indice_columna)
    print("="*50)
    
    # Obtiene el valor de grupo actual: inicialmente el primer valor de la primera columna
    grupo_actual = df.iloc[0, indice_columna - 1]  
    print('Grupo actual: ',grupo_actual)
    print("="*50)

    # Inicializa diccionario con subtotales del grupo actual en 0 para cada columna num√©rica 
    subtotales_grupo = {columna: 0 for columna in columnas_numericas}  
    print('Subtotales del grupo: ',subtotales_grupo)
    print("="*50)
    
    # Inicializa lista para almacenar filas a concatenar
    rows_to_concat = []  
    print('Filas a concatenar: ',rows_to_concat)
    print("="*50)
    
    for index, fila in df.iterrows():   # Iterar sobre las filas del DataFrame
        print('valor de la fila anterior: ',fila.iloc[indice_columna - 1])
        print('Grupo actual: ',grupo_actual)
        print("-"*50)

        # En caso de que el valor de la columna de agrupaci√≥n sea "diferente" al grupo actual
        if fila.iloc[indice_columna - 1] != grupo_actual: 
            subtotal = {'A': f"Subtotal {grupo_actual}"}                                            # Crea una fila con el nombre del grupo
            print('Subtotal: ',subtotal)
            print("-"*50)
            subtotal.update({columna: subtotales_grupo[columna] for columna in columnas_numericas}) # A√±ade los subtotales del grupo al diccionario
            print('Subtotal actualizado: ',subtotales_grupo)
            print("-"*50)
            rows_to_concat.append(subtotal)                                                         # A√±ade la fila de subtotal a la lista de filas a concatenar
            print('Filas a concatenar: ',rows_to_concat)
            print("-"*50)
            subtotales_grupo = {columna: 0 for columna in columnas_numericas}                       # Reinicia los subtotales para el nuevo grupo
            print("="*50)
            print('Reinicio de Subtotales del grupo',subtotales_grupo)
            print("-"*50)
            grupo_actual = fila.iloc[indice_columna - 1]                                            # Actualiza el grupo actual con el valor de la fila actual
            print('Grupo actualizado: ',grupo_actual)
            print("-"*50)

        # Sin importar si el grupo es igual o diferente, itera sobre las columnas num√©ricas para actualizar los subtotales                
        for columna in columnas_numericas:  
            subtotales_grupo[columna] += fila[columna]      # Suma el valor de la fila actual al subtotal del grupo actual
            print('itera para actualizar los subtotales')
            print('Subtotales del grupo actual: ',subtotales_grupo)
            print("-"*50)

        # Sin importar si el grupo es igual o diferente, siempre agrega la fila actual al final de la lista de filas a concatenar
        rows_to_concat.append(fila)
        print('Filas a concatenar: ',rows_to_concat)
        print("="*50)
    
    print("="*50)
    print(df)
    print("="*50)

    # Agregar los subtotales del √∫ltimo grupo
    subtotal = {'A': f"Subtotal {grupo_actual}"}
    subtotal.update({columna: subtotales_grupo[columna] for columna in columnas_numericas})
    rows_to_concat.append(subtotal)
    
    # Concatena las filas de subtotal al DataFrame original
    df = pd.concat([pd.DataFrame([row]) for row in rows_to_concat], ignore_index=True) # 
    
    return df

# Aplica la funci√≥n para insertar filas con subtotal y calcular subtotales
df = insertar_fila_subtotal(df.copy())

# Imprime el dataframe con las filas insertadas, subtotales y subtotales calculados
print(df)

Columnas num√©ricas:  Index(['B', 'C', 'D'], dtype='object')
==================================================
Indice de columna:  1
==================================================
Grupo actual:  a
==================================================
Subtotales del grupo:  {'B': 0, 'C': 0, 'D': 0}
==================================================
Filas a concatenar:  []
==================================================
valor de la fila anterior:  a
Grupo actual:  a
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 1, 'C': 0, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 1, 'C': 1, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 1, 'C': 1, 'D': 2}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object]
==================================================
valor de la fila anterior:  a
Grupo actual:  a
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 3, 'C': 1, 'D': 2}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 3, 'C': 3, 'D': 2}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 3, 'C': 3, 'D': 5}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object]
==================================================
valor de la fila anterior:  a
Grupo actual:  a
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 6, 'C': 3, 'D': 5}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 6, 'C': 6, 'D': 5}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 6, 'C': 6, 'D': 9}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object]
==================================================
valor de la fila anterior:  b
Grupo actual:  a
--------------------------------------------------
Subtotal:  {'A': 'Subtotal a'}
--------------------------------------------------
Subtotal actualizado:  {'B': 6, 'C': 6, 'D': 9}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}]
--------------------------------------------------
==================================================
Reinicio de Subtotales del grupo {'B': 0, 'C': 0, 'D': 0}
--------------------------------------------------
Grupo actualizado:  b
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 4, 'C': 0, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 4, 'C': 4, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 4, 'C': 4, 'D': 5}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object]
==================================================
valor de la fila anterior:  b
Grupo actual:  b
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 4, 'D': 5}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 9, 'D': 5}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 9, 'D': 11}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object]
==================================================
valor de la fila anterior:  b
Grupo actual:  b
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 9, 'D': 11}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 15, 'D': 11}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 15, 'D': 18}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object]
==================================================
valor de la fila anterior:  c
Grupo actual:  b
--------------------------------------------------
Subtotal:  {'A': 'Subtotal b'}
--------------------------------------------------
Subtotal actualizado:  {'B': 15, 'C': 15, 'D': 18}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}]
--------------------------------------------------
==================================================
Reinicio de Subtotales del grupo {'B': 0, 'C': 0, 'D': 0}
--------------------------------------------------
Grupo actualizado:  c
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 7, 'C': 0, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 7, 'C': 7, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 7, 'C': 7, 'D': 8}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}, A    c
B    7
C    7
D    8
Name: 6, dtype: object]
==================================================
valor de la fila anterior:  c
Grupo actual:  c
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 7, 'D': 8}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 15, 'D': 8}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 15, 'C': 15, 'D': 17}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}, A    c
B    7
C    7
D    8
Name: 6, dtype: object, A    c
B    8
C    8
D    9
Name: 7, dtype: object]
==================================================
valor de la fila anterior:  d
Grupo actual:  c
--------------------------------------------------
Subtotal:  {'A': 'Subtotal c'}
--------------------------------------------------
Subtotal actualizado:  {'B': 15, 'C': 15, 'D': 17}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}, A    c
B    7
C    7
D    8
Name: 6, dtype: object, A    c
B    8
C    8
D    9
Name: 7, dtype: object, {'A': 'Subtotal c', 'B': 15, 'C': 15, 'D': 17}]
--------------------------------------------------
==================================================
Reinicio de Subtotales del grupo {'B': 0, 'C': 0, 'D': 0}
--------------------------------------------------
Grupo actualizado:  d
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 0, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 9, 'D': 0}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 9, 'C': 9, 'D': 10}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}, A    c
B    7
C    7
D    8
Name: 6, dtype: object, A    c
B    8
C    8
D    9
Name: 7, dtype: object, {'A': 'Subtotal c', 'B': 15, 'C': 15, 'D': 17}, A     d
B     9
C     9
D    10
Name: 8, dtype: object]
==================================================
valor de la fila anterior:  d
Grupo actual:  d
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 19, 'C': 9, 'D': 10}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 19, 'C': 19, 'D': 10}
--------------------------------------------------
itera para actualizar los subtotales
Subtotales del grupo actual:  {'B': 19, 'C': 19, 'D': 21}
--------------------------------------------------
Filas a concatenar:  [A    a
B    1
C    1
D    2
Name: 0, dtype: object, A    a
B    2
C    2
D    3
Name: 1, dtype: object, A    a
B    3
C    3
D    4
Name: 2, dtype: object, {'A': 'Subtotal a', 'B': 6, 'C': 6, 'D': 9}, A    b
B    4
C    4
D    5
Name: 3, dtype: object, A    b
B    5
C    5
D    6
Name: 4, dtype: object, A    b
B    6
C    6
D    7
Name: 5, dtype: object, {'A': 'Subtotal b', 'B': 15, 'C': 15, 'D': 18}, A    c
B    7
C    7
D    8
Name: 6, dtype: object, A    c
B    8
C    8
D    9
Name: 7, dtype: object, {'A': 'Subtotal c', 'B': 15, 'C': 15, 'D': 17}, A     d
B     9
C     9
D    10
Name: 8, dtype: object, A     d
B    10
C    10
D    11
Name: 9, dtype: object]
==================================================
==================================================
   A   B   C   D
0  a   1   1   2
1  a   2   2   3
2  a   3   3   4
3  b   4   4   5
4  b   5   5   6
5  b   6   6   7
6  c   7   7   8
7  c   8   8   9
8  d   9   9  10
9  d  10  10  11
==================================================
             A   B   C   D
0            a   1   1   2
1            a   2   2   3
2            a   3   3   4
3   Subtotal a   6   6   9
4            b   4   4   5
5            b   5   5   6
6            b   6   6   7
7   Subtotal b  15  15  18
8            c   7   7   8
9            c   8   8   9
10  Subtotal c  15  15  17
11           d   9   9  10
12           d  10  10  11
13  Subtotal d  19  19  21

In [58]:
# ============================================================================================================
# Exportar el DataFrame reporte_final a un archivo Excel
# ============================================================================================================

Hacer un reporte en excel:

Encabezado de dos filas (sin datos):
En la primera fila, el nombre de la empresa: "Empresa SHINA"
Segunda fila vac√≠a

En las siguientes filas se insertar√°n los datos:
Tercera fila: informaci√≥n de saldo inicial: registro con id_grp = 5
Cuarta fila vac√≠a
A partir de la quinta fila los registros con id_grp =  4 ordenados por valor ascendente de la columna del primer inicial
Siguiente fila que calcule subtotal de registros con id_grp =  4
Siguiente fila vacia
Siguiente grupo de filas,  los registros con id_grp =  3 ordenados por valor ascendente de la columna del primer inicial
Siguiente fila que calcule subtotal de registros con id_grp =  3
Siguiente fila vacia
Siguiente grupo de filas,  los registros con id_grp =  2 ordenados por valor ascendente de la columna del primer inicial
Siguiente fila que calcule subtotal de registros con id_grp =  2
Siguiente fila vacia
Siguiente fila que calcule el saldo final como la suma de registro con id_grp = 5 + subtotal de registros con id_grp =  2 + subtotal  de registros con id_grp = 3 + subtotal  de registros con id_grp =  4